arb-dir: lib/locale/l10n

template-arb-file: app_en.arb

output-dir: lib/generated

use-deferred-loading: false

output-localization-file: app_localizations.dart

preferred-supported-locales: en

untranslated-messages-file: untranslated_messages.txt

translate-missing-messages: true

use-json-format: false
