name: flutter_gp5
description: "Project #11"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.4.1
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.1.0
  iconly: ^1.0.1
  logger: ^2.3.0
  uuid: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^1.0.3
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  country_flags: ^3.0.0
  material_design_icons_flutter: ^7.0.7296
  telephony: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
    - assets/images/google-logo.png
    - assets/images/klinik-logo-01.png
    - assets/images/klinik-logo-02.png
    - assets/images/klinik-logo-03.png
    - assets/images/klinik-logo-04.png
