name: flutter_gp5
description: "Project #11"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.4.1
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^1.0.3
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
