name: flutter_gp5
description: "Project #11"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_storage: ^12.4.3
  firebase_app_check: ^0.3.2+3
  cloud_firestore: ^5.6.4
  iconly: ^1.0.1
  intl_phone_field: ^3.2.0
  logger: ^2.5.0
  uuid: ^4.5.1
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.0.17
  bloc: ^9.0.0
  equatable: ^2.0.3
  flutter_bloc: ^9.0.0
  country_flags: ^3.0.0
  material_design_icons_flutter: ^7.0.7296
  file_picker: ^8.0.7
  image_picker: ^1.1.2
  path: ^1.9.0
  permission_handler: ^11.3.1
  meta: ^1.15.0
  path_provider: ^2.1.5
  get_it: ^8.0.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dartx: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  freezed: ^2.5.8

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
    - assets/images/google-logo.png
    - assets/images/klinik-logo-01.png
    - assets/images/klinik-logo-02.png
    - assets/images/klinik-logo-03.png
    - assets/images/klinik-logo-04.png
    - assets/images/home.png
    - assets/images/msg.png
    - assets/hospitals.json
    - assets/icons/information.svg
    - assets/privacy_policy.txt
    - assets/terms_of_use.txt