// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApN5DBcd6N8qwGlGrv4UwoE6kfqK4Pbkk',
    authDomain: 'gp5-firebase-60ae9.firebaseapp.com',
    projectId: 'gp5-firebase-60ae9',
    storageBucket: 'gp5-firebase-60ae9.appspot.com',
    messagingSenderId: '886581177450',
    appId: '1:886581177450:web:410bbb7ff3bffcdf522e13',
    measurementId: 'G-CHS6N277ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApN5DBcd6N8qwGlGrv4UwoE6kfqK4Pbkk',
    appId: '1:628322144355:android:4059e42be8af674832a856',
    messagingSenderId: '628322144355',
    projectId: 'klinik-322ca',
    storageBucket: 'klinik-322ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgM0bGjXeruRt7S4bR9D2qsd3D7GUBAlc',
    appId: '1:628322144355:ios:aa6516a2e32978c032a856',
    messagingSenderId: '628322144355',
    projectId: 'klinik-322ca',
    storageBucket: 'klinik-322ca.firebasestorage.app',
    iosBundleId: 'com.example.flutterGp5',
  );
}